### PR TITLE
Change HTTP messages to <sourcecode>

### PR DESCRIPTION
**Pull request by mnot**
For #771.

### CODE REVIEW

**Review by reschke — COMMENTED** [review]
I don't think this is a good change.

As long as it is not clear what the right approach is, changing this is premature.

**Comment by mnot** [comment]
It's a draft, for when we get clarity. Based upon the current state of discussion on 7991bis, it seems likely we'll go this way.

**Comment by reschke** [comment]
FWIW, re the argument "minimize the amount of diffs during AUTH48" - we already have ton of unavoidable diffs, due to the extensions we use (for instance, for cross-references between documents).

**Comment by reschke** [comment]
FWIW, removing "x:indent-with" will change the indentation in the text output, creating lot of diffs. Is this intended and ok?

**Comment by mnot** [comment]
I think so; it aligns with other usage.

**Pull request merged**
