### PR TITLE
Only use absolute-form if it's a proxy

### LINKED ISSUE #896: Ben Kaduk's DISCUSS on Semantics - absolute URIs as request targets
_From @kaduk -_

Let's discuss whether the currently specified procedures for reconstructing the target URI from a request-target in absolute-form provide adequate security properties, at the origin server. I'm specifically concerned about taking the scheme directly from the request target, i.e., making the distinction between the "http" and "https" schemes. The simple procedure of "take the scheme from the request-target" would seem to allow for the client to cause the server to engage processing for the "https" origin without receiving the protection that https is supposed to provide. (The converse case does not immediately seem to present much risk but is probably worth preventing as well on general principles of retaining consistency.) I don't remember seeing any text that would require the server to validate the scheme from the request-target against the actual properties of the transport (or the configured fixed URI scheme as might be provisioned with a trusted outbound gateway, etc.) While we do reference §7.4 of [Semantics] with a note that reconstructing the target URI is only part of the process of identifying a target resource, that part of [Semantics] does not mention scheme validation as part of rejecting misdirected requests.

Does the origin server need to validate the scheme from an absolute-form request-target? What is the scope of consequences if it fails to do so?

### PR DESCRIPTION
**Pull request by mnot**
Fixes #896.

### CODE REVIEW

**Review by reschke — CHANGES_REQUESTED** [review]
That seems to leave the algorithm for determining the reequest URI undefined if the form is "absolute-form", and the recipient it not a proxy.

**Comment by mnot** [comment]
Ah - I forgot to update that, thanks. Will do when I’m next in front of computer.

**Review by royfielding — CHANGES_REQUESTED** [review]
Absolutely not.

**Comment by royfielding** [comment]
Closing as this is not in scope.

**Pull request closed without merging**
