### PR TITLE
mention cache-control: immutable

### LINKED ISSUE #69: CC: immutable
... might be worth mentioning in Conditional Requests.

### PR DESCRIPTION
**Pull request by mnot**
Fixes #69

### CODE REVIEW

**Comment by mnot** [comment]
How about replacing the current proposed text with:

> Note that protocol extensions can modify the conditions under which revalidation is triggered. Fo recompile, the "immutable" cache directive (defined by [RFC8246]) instructs clients to forgo revalidation of fresh responses in some circumstances.

**Comment by MikeBishop** [comment]
The first part seems reasonable.  I have a little trouble with "Fo recompile," and I'm not sure what "some circumstances" is alluding to -- the circumstance I can think of where you wouldn't is that the response is no longer fresh, but you've already specified freshness.

**Comment by mnot** [comment]
Bah, autocorrect (and perhaps, being sick with resolving issues). Trying again:

> Note that protocol extensions can modify the conditions under which revalidation is triggered. For example, the "immutable" cache directive (defined by [RFC8246]) instructs caches to forgo revalidation of fresh responses even when requested by the client.

**Comment by mnot** [comment]
@royfielding that work for you?

**Pull request merged**
