### PR TITLE
Clarify that the charset parameter value is case-insensitive due to the definition in RFC 2046 (closes #13)

### LINKED ISSUE #13: RFC 7231 content-type charset param case sensitivity
https://greenbytes.de/tech/webdav/rfc7231.html#media.type

> The type, subtype, and parameter name tokens are case-insensitive. Parameter values might or might not be case-sensitive, depending on the semantics of the parameter name. The presence or absence of a parameter might be significant to the processing of a media-type, depending on its definition within the media type registry.

...it then continues showing examples that imply that the charset value is case-insensitive (which is correct), but it would be helpful if it cited RFC 2046 which defines charset's case  sensitivity.

### PR DESCRIPTION
**Pull request by reschke**

### CODE REVIEW

**Comment by royfielding** [comment]
It's an example. The fact that charset names are case-insensitive is both well-known and defined (correctly) one inch below that.  Adding an out-dated reference does not help the example.  If this is somehow a problem (for whatever reason), just delete that one line of the example.

**Comment by reschke** [comment]
@royfielding  - not convinced. The section you are referring to is about the "charset" ABNF production, not the parameter called "charset" in media types. These are not the same; the former is token-shaped and only used in "Accept-Charset", the latter is a parameter value.

Maybe there's more to clarify here. Maybe <https://greenbytes.de/tech/webdav/draft-ietf-httpbis-semantics-02.html#charset> should be eliminated where it is right now - it's only used by Accept-Charset (see also #61)

**Comment by reschke** [comment]
More feedback appreciated.

I would recommend that we apply this pull request and also consider removing the "charset" ABNF production, given the fact that it is only used in one header field definition.

**Comment by royfielding** [comment]
This is confusing too many things.

First, we have a set of four examples of things that are equivalent.  If you want to remove one of them just because we haven't yet defined that in the spec (two inches down), that's fine.  Just delete that line. It is not worth the added explanation.

Second, the section on charset defines the charset property as a relevant semantic for media types and normatively refers to the correct spec: RFC6365. The reference to how to register charset values is informative. This is a subsection of media types. We could change the order here and define charset as a parameter before a subsection on equivalent examples (if we want to keep all four examples).

Third, the rule "charset" is defined here for historical reasons because that is where I think a reader would look for it. If you want to move the ABNF fragment into Accept-Charset instead, that's fine with me as well.  But they are not two different things. The charset parameter and the charset token are both defined as case-insensitive because of the semantics here.

I am really not good at making interactive changes via pull requests, so it may be easier to commit a first draft and iterate within git instead of via PRs.

**Comment by reschke** [comment]
Actually, RFC 6365 is "Terminology Used in Internationalization in the IETF", and we are referring to it to define the term "character encoding scheme".

**Comment by royfielding** [comment]
and it is also the normative definition of "[charset](https://tools.ietf.org/html/rfc6365#page-8)" (the older RFC is only the registration mechanism).

**Comment by royfielding** [comment]
I think I see what you mean, though. For the ABNF definition of charset, the normative definition is in RFC2978 as

>  mime-charset = 1*mime-charset-chars
>   mime-charset-chars = ALPHA / DIGIT / "!" / "#" / "$" / "%" / "&" / "'" / "+" / "-" / "^" / "_" /  "`" / "{" / "}" / "~"
>  ALPHA        = "A".."Z"    ; Case insensitive ASCII Letter
>  DIGIT        = "0".."9"    ; Numeric digit

**Pull request merged**
