### PR TITLE
Lars Eggert COMMENT draft-ietf-httpbis-messaging-16  (for #852)

### PR DESCRIPTION
**Pull request by reschke**

### CODE REVIEW

**Comment by royfielding** [comment]
It is spelled as Acknowledgments in every RFC. Fix the one inconsistent case instead.

**Comment by reschke** [comment]
> It is spelled as Acknowledgments in every RFC. Fix the one inconsistent case instead.

FWIW, I checked the style guide. Will check again.

**Comment by royfielding** [comment]
Well, FFS, the style guide also says to use either US spelling or British spelling, but not both. It is spelled Acknowledgments in the US and all RFCs prior to that style guide. The RFC editor deliberately changed my text to Acknowledgments the last time this came up. I don't care which way it is spelled.

**Review by royfielding — APPROVED** [review]
I think we should commit this now and let the RFC editor decide on spelling.

**Pull request merged**
