### PR TITLE
Clarify edge case of If-Match and If-Unmodified-Since for retrieval requests like GET (fixes #800)

### LINKED ISSUE #800: GET conditioned over If-Match
Consider a GET request conditioned over `If-Match` (I know it's nonsense, but the spec allows it). If the origin server does not have a current representation for the target resource, then the condition is false:
https://github.com/httpwg/http-core/blob/df2fefd530357474ecc7b0ef2f5b324371cdc878/draft-ietf-httpbis-semantics-latest.xml#L6963-L6978
Therefore, the server should respond 412:
https://github.com/httpwg/http-core/blob/df2fefd530357474ecc7b0ef2f5b324371cdc878/draft-ietf-httpbis-semantics-latest.xml#L7450-L7459
However, both Apache and Nginx responded 404.
Did I misunderstand some part of the specification, or are the servers violating the spec?

### PR DESCRIPTION
**Pull request by reschke**

### CODE REVIEW

**Review by royfielding — CHANGES_REQUESTED** [review]
This doesn't look right -- I don't want a 200 response if the precondition fails unless it is specifically If-Modified-Since or If-None-Match. The edge case was about 404, not 200.

**Comment by royfielding** [comment]
And I'll reiterate again that we do not need to specify this edge case. The response should be 404 because there is no selected representation upon which to test the 412.

**Comment by reschke** [comment]
Hm. The spec doesn't seem to allow the 404, though.

I guess we should park this and get the specs out though.

**Comment by royfielding** [comment]
> Hm. The spec doesn't seem to allow the 404, though.

This is defined in "When to Evaluate":

> A server MUST ignore all received preconditions if its response to the same request without those conditions, prior to processing the request content, would have been a status code other than a <x:ref>2xx (Successful)</x:ref> or <x:ref>412 (Precondition Failed)</x:ref>.

IOW, if the request would have been 404 without the precondition then it MUST be 404 with the precondition.

**Comment by royfielding** [comment]
I closed the issue instead.

**Comment by liyishuai** [comment]
Let me check my understanding:
A server MUST first preprocess the request without conditions, and check whether the status code can be determined, before evaluating the conditions.
If so, should we replace all occurrences "precondition" with "condition"? since they're not evaluated at the very first, conceptually.

**Pull request closed without merging**
