### PR TITLE
make section xrefs in tables more concise and consistent (editorial)

### PR DESCRIPTION
**Pull request by royfielding**
did I mention that I hate line breaks in text table crossrefs?

This makes the text format much better, but the html output is worse because the stylesheet isn't padding cells. I am hoping that would be a simple fix.

### CODE REVIEW

**Comment by reschke** [comment]
Hm.

I'm not convinced that we should optimize for the text output.

I can revise the table padding, but need to be careful with that.

**Comment by reschke** [comment]
Yes, it needs to come out right with xml2rfc's HTML output.

**Comment by reschke** [comment]
@royfielding - https://github.com/reschke/xml2rfc/commit/6e0313585f451aa21615b90e3cd203cb82ae0a97

**Comment by royfielding** [comment]
I was thinking about this last night and realized that "See" as a column heading might offend someone. I will try changing that to "Ref."

**Pull request merged**
