### PR TITLE
update port references

### LINKED ISSUE #36: Port registration
Just a reminder to update the port registration appropriately.

### PR DESCRIPTION
**Pull request by mnot**
Fixes #36.

### CODE REVIEW

**Comment by mnot** [comment]
No, all entries for 80 and 443 that use TCP or UDP. I have no opinion about SCTP, and don't want to take over authority for it in these specs.

I think the instruction in the PR is sufficient; all we're doing is changing (or adding) references.

**Comment by reschke** [comment]
My experience with IANA is that they want precise instructions. It also helps readers/reviewers understand what's happening.

**Comment by reschke** [comment]
See https://github.com/httpwg/http-core/pull/246/commits/8835112d77b9c3d218c9032fa17f29bdc0761af9 - which begs the question whether we should also update assignee/contact for "www-http" which are currently assigned to TimBL.

**Comment by mnot** [comment]
Works for me. @reschke you now OK?

My instinct is to leave www-http alone.

**Pull request merged**
