### PR TITLE
import the 421 (Misdirected Request) status code from RFC7540

### LINKED ISSUE #622: import 421 (Misdirected Request) Status Code from h2
I think we need to copy the 421 status code definition from [Section 9.1.2 of RFC7540](https://httpwg.org/specs/rfc7540.html#MisdirectedRequest) since it is generally applicable for rejecting a misdirected request.

### PR DESCRIPTION
**Pull request by royfielding**
Fixes #622

### CODE REVIEW

**Comment by royfielding** [comment]
I haven't checked the errata yet, but I have to go now and this is worth reviewing.

**Review by reschke — APPROVED** [review]

**Comment by reschke** [comment]
Maybe end the last paragraph with: "Because of this default, senders in general should mark it as non-cacheable using ...".

**Comment by reschke** [comment]
sry, accidentally merged early; we still need to deal with the erratum

**Comment by royfielding** [comment]
I don't understand what happened here, but master does not contain the changes that github thinks have been merged.

**Comment by reschke** [comment]
Yes, I tried to undo my mistake.

**Review by martinthomson — COMMENTED** [review]
A much belated approval from me.  This looks good.

**Pull request merged**
