### PR TITLE
Move text about CRLF up

### LINKED ISSUE #68: message parsing robustness
... is awfully far from the definition of the message format; IME people read the start of section 3 in isolation and don't see the text below. Maybe move 3.5 up?

### PR DESCRIPTION
**Pull request by mnot**
Fixes #68.

### CODE REVIEW

**Comment by mnot** [comment]
As suggested in the issue. Looking at it, more text could be moved up, or the entire section could be moved up (e.g., as a subsection of where this text went), but this seemed reasonable.

**Comment by mnot** [comment]
-1; this needs to be where CRLF is used, not a different section.

**Comment by mnot** [comment]
Like that? Wasn't sure what you meant by "moving HTTP version up..."

**Comment by royfielding** [comment]
> Like that? Wasn't sure what you meant by "moving HTTP version up..."

I meant literally move the section titled "HTTP Version" up above the section titled "Message" and then move "Parsing" to a subsection of "Message". I'll see if I can tweak it.

**Comment by reschke** [comment]
Would this close #68?

**Pull request merged**
