### PR TITLE
Accept-Ranges is for Origin Servers

### PR DESCRIPTION
**Pull request by mnot**
For #857

### CODE REVIEW

**Comment by mnot** [comment]
See, however, [this comment from Roy in 1996](https://web.archive.org/web/20010222161642/http://www.ics.uci.edu/pub/ietf/http/hypermail/1996q2/0615.html):

>The following paragraphs are absolutely wrong and must be deleted:
>
>The Accept-Ranges MUST NOT be added to a response by a proxy (i.e., it
>may only be added by the origin server), MUST NOT be forwarded by a
>proxy that does not support the Range header, and MUST NOT be returned
>to a client whose HTTP version is less than HTTP/1.1.
> 
>  Note: this rule allows a client to be reasonably sure that a
>  subsequent Range request on the entity will not accidentally
>  transfer the entire entity.  However, the subsequent Range request
>  may follow a different request chain, and so there is a small
>  chance that the entire entity will be returned in a response.
>
> and the paragraph below it should begin with "Servers ..." instead
> of "Origin servers ...".
>
> The reason is because the Range header field is interpreted by the
> next inbound server that has the entity cached -- not necessarily
> the origin server -- and thus 14.5 is SEVERELY BROKEN in draft 04a.

Roy, any thoughts? To my mind, a proxy (as opposed to a gateway) adding Accept-Ranges to a response is... surprising. It's conflating origin capabilities with proxy capabilities.

**Comment by reschke** [comment]
Hm. Why would we forbid non-origin servers to implement ranges?

**Comment by royfielding** [comment]
> Roy, any thoughts? To my mind, a proxy (as opposed to a gateway) adding Accept-Ranges to a response is... surprising. It's conflating origin capabilities with proxy capabilities.

I think that was why it was left as is -- I was reading it as a server capability, not an origin capability, and the paragraphs as a limitation on using Range requests. Someone else wanted it to be only an origin header field. So, fine. I am pretty sure implementations ignore it anyway.

**Comment by mnot** [comment]
The problem is that the current text uses both 'server' and 'origin server', so it sends conflicting messages.

**Comment by reschke** [comment]
So why not remove the restriction on "origin servers" consistently?

**Comment by MikeBishop** [comment]
I'm familiar with a caching layer that will request the entire object upstream for caching purposes and then serve range requests out of the cached resource.  It seems entirely reasonable that an intermediary might do something similar.

**Comment by mnot** [comment]
@MikeBishop I'm familiar with that one too -- but it's a gateway, acting as an origin.

**Comment by reschke** [comment]
My understanding is that we allow all servers to process range requests, but only allow origin servers to indicate support (and even that inconsistently: "A server that does not support any kind of range request for the target resource MAY send Accept-Ranges: none to advise the client not to attempt a range request.")

As far as I can tell, this is clearly a mistake, and removing the single instance of "origin" here would fix that.

**Comment by royfielding** [comment]
I think "fixing" this field is hopeless. It was added late in the game, as a form of advertising for a feature that wasn't always supported, and didn't take into consideration all of the reasons for making Range requests. Hence, I think we should go with Mark's clarification that this field is only set by origin servers, but re-emphasize that it is advisory only and that most clients ignore it because they want a 200 response when range is not supported.

**Comment by reschke** [comment]
Hm, me confused. Isn't the right fox just to replace all mentions of "origin server" with just "server"? What am I missing?

**Comment by royfielding** [comment]
Okay, I went back and re-read the full discussion at

  https://lists.w3.org/Archives/Public/ietf-http-wg-old/1996MayAug/0387.html
  https://lists.w3.org/Archives/Public/ietf-http-wg-old/1996MayAug/0411.html

and the final resolution should have matched Lou's comment. Specifically, the purpose of Netscape's implementation of Accept-Ranges was to indicate if any of the servers/caches along the chain supported Range requests.

So, now I am back to agreeing with 1996-me and Julian that the fault is in the spec.

**Comment by royfielding** [comment]
replaced by #902

**Pull request closed without merging**
