### PR TITLE
define the Message Abstraction as an ADT rather than as a message

### LINKED ISSUE #540: Semantics: "5.3. Header Fields" -> "5.3. Header and Trailer Fields"?

### PR DESCRIPTION
**Pull request by royfielding**
This fixes #540 and a lot more in the process.

- move Fields to its own section before the message abstraction;
- define the Message Abstraction as an ADT so that it makes sense regardless of the message syntax;
- define and forward reference the control data;
- move protocol version definition up and normative requirements to control data;
- clearly define the header and trailer lookup tables as abstractions and the sections as where to look for those fields;
- define the payload and clean up old mentions of message body and payload body;
- merge paragraphs that had duplicate definitions in trailers and payload.

Normally I would separate the commit into moves first and then changes, but I have run out of time and would rather have reviews of the end result. We can do that in a separate PR if needed.

### CODE REVIEW

**Comment by royfielding** [comment]
also fixes #532

**Review by reschke — COMMENTED** [review]
This is indeed hard to review.

Should I try to split this into separate PRs?

**Comment by royfielding** [comment]
Yeah, the diff is hopeless. I will start breaking it out into separate pieces.

**Comment by royfielding** [comment]
Replaced by #551 + #554 + #555 + #557

**Pull request closed without merging**
